name: Rust

on:  
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: DEBIAN_FRONTEND=noninteractive sudo apt-get install xorg-dev libglu1-mesa-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate opcodes
      run: cargo run -- json > opcodes.json
    - name: Upload opcodes
      uses: actions/upload-artifact@v3.1.0
      with:
        name: opcodes
        # A file, directory or wildcard pattern that describes what to upload
        path: ./opcodes.json
        if-no-files-found: error


